import dotenv from 'dotenv'

dotenv.config()

export const {
  APP_PORT,
  NODE_ENV,
  DB_USERNAME,
  DB_PASSWORD,
  DB_HOST,
  DB_PORT,
  DB_NAME,
  DB_STRING,
  SESS_NAME,
  SESS_SECRET,
  SESS_LIFETIME,
  REDIS_URL,
  AWS_IAM_ROLE_ACCESS_KEY_ID,
  AWS_IAM_ROLE_SECRET_ACCESS_KEY,
  AWS_IAM_ROLE_REGION,
  IMAGE_UPLOAD_S3_BUCKET_NAME,
  PUBLIC_READ_S3_BUCKET_NAME
} = process.env

export const IN_PROD = NODE_ENV === 'production'
