import dotenv from 'dotenv'

dotenv.config()

export const {
  APP_PORT,
  DB_HOST,
  DB_ROOT_USER,
  DB_ROOT_USER_PASSWORD,
  DB_NAME,
  REDIS_HOST,
  SESSION_NAME,
  SESSION_SECRET,
  AWS_IAM_ROLE_ACCESS_KEY_ID,
  AWS_IAM_ROLE_SECRET_ACCESS_KEY,
  AWS_IAM_ROLE_REGION,
  IMAGE_UPLOAD_S3_BUCKET_NAME,
  PUBLIC_READ_S3_BUCKET_NAME,
  GEMINI_API_KEY
} = process.env

export const IN_PROD = true
