mutation {
    signUp(username:"SamC", password:"Banana@1234", firstName:"Sam", lastName:"Convoy", gender:"Male", country:"USA", primaryEmail:"SamConvoy@gmail.com"){
        firstName
    }
}

mutation {
    signUp(username:"JaneC", password:"Banana@1234", firstName:"Jane", lastName:"Convoy", gender:"Female", country:"USA", primaryEmail:"JaneConvoy@gmail.com"){
        firstName
    }
}

mutation {
    signUp(username:"KaneC", password:"Banana@1234", firstName:"Kane", lastName:"Convoy", gender:"Male", country:"UK", primaryEmail:"KaneConvoy@gmail.com"){
        firstName
    }
}

mutation {
    signIn(username:"SamC", password:"Banana@1234"){
        firstName
    }
}

mutation {
    signIn(username:"JaneC", password:"Banana@1234"){
        firstName
    }
}

mutation {
    signIn(username:"KaneC", password:"Banana@1234"){
        firstName
    }
}

mutation {
    signOut
}

#--------------------------------------------------------------------------

# Projects

mutation {
    createProject(title:"Project Alpha", description:"AI based FullStack Project") {
        id
    }
}

mutation {
    createProject(title:"Project Beta", description:"IOT based FullStack Project", members:["65755ce1663be023e8a16df5"]) {
        id
    }
}

mutation {
    updateProject(id:"65916e30eb53ee8e45ff0bcf", description:"IOT development Project") {
        id
    }
}

mutation {
    deleteProject(id:"65916e30eb53ee8e45ff0bcf")
}

query projects {
        projects {
            id
            title
            description
            status
            defaultProcess {
                id
            }
        }
}

query project {
        project(id:"65916b45eb53ee8e45ff0bbc") {
            id
            title
            description
            owner {
                id
            }
            members {
                id
                username
                firstName
                lastName
                gender
            }
            status
            processes {
                id
                title
                description
                status
                priority
            }
            defaultProcess {
                id
            }
        }
}

#--------------------------------------------------------------------

# Processes

query processes {
    processes(projectId:"659251af749175ea95e8dfec") {
        id
        project {
            id
        }
        title
        description
        status
        priority
    }
}

query process {
    process(id:"65916b45eb53ee8e45ff0bbe") {
        id
        project {
            id
        }
        title
        description
        status
        priority
        managers {
            id
            username
            firstName
            lastName
            gender
        }
        phases {
            id
            process {
                id
            }
            title
            description
            order
            endDate
            endTime
            status
        }
    }
}

mutation {
    createProcess(projectId:"65916b45eb53ee8e45ff0bbc", title:"Complementary Process", description:"Additional Steps", priority:"Normal") {
        id
    }
}

mutation {
    createProcess(projectId:"659251af749175ea95e8dfec", title:"Secondary Process", description:"Alternative Steps", priority:"Low", managers:["65755ce1663be023e8a16df5"]) {
        id
    }
}

mutation {
    updateProcess(id:"65916b45eb53ee8e45ff0bbe", description:"Additional Steps") {
        id
    }
}

mutation {
    deleteProcess(id:"65925227749175ea95e8dff8")
}

mutation {
    addProcessManagers(id:"659251af749175ea95e8dfee", managers:["65755ce1663be023e8a16df5"]) {
        id
    }
}

mutation {
    removeProcessManagers(id:"659251af749175ea95e8dfee", managers:["65755ce1663be023e8a16df5"]) {
        id
    }
}

mutation {
    changeDefaultProcess(id:"659271910603aab10cb73966") {
        id
    }
}

#------------------------------------------------------------------------------------

# phases

mutation {
    createPhase(processId:"659271910603aab10cb73966", title:"Dev Phase", description:"Web Development Phase", endDate:"2020-12-31", endTime:"23:59", timezoneOffset:330) {
        id
    }
}

mutation {
    createPhase(processId:"659271910603aab10cb73966", title:"Testing Phase", description:"Testing Website in Test Environment", endDate:"2021-01-05", timezoneOffset:330) {
        id
    }
}

mutation {
    updatePhase(id:"6592d70cd6bddda006bf359b", description:"Testing Website") {
        id
    }
}

mutation {
    deletePhase(id:"6592d70cd6bddda006bf359b")
}

query phases {
    phases(processId:"659271910603aab10cb73966") {
        id
        process {
            id
        }
        title
        description
        order
        endDate
        endTime
        timezoneOffset
        status
        phaseMembers {
            id
        }
    }
}

query phase {
    phase(id:"6592d9f0fc4b59f0f2b54b32") {
        id
        process {
            id
        }
        title
        description
        order
        startDate
        endDate
        endTime
        timezoneOffset
        status
        phaseMembers {
            id
            username
            firstName
            lastName
            gender
        }
        phaseAdmins {
            id
            username
            firstName
            lastName
            gender
        }
        tasks {
            id
            title
            description
            endDate
            endTime
            timezoneOffset
            status
        }
    }
}

mutation {
    addPhaseAdmins(id:"6592d9f0fc4b59f0f2b54b32", admins:["65755ce1663be023e8a16df5","65754ade55df1cea083fdbb9"]) {
        id
    }
}

mutation {
    removePhaseAdmins(id:"6592d9f0fc4b59f0f2b54b32", admins:["65754ade55df1cea083fdbb9"]) {
        id
    }
}

mutation {
    addPhaseMembers(id:"6592d9f0fc4b59f0f2b54b32", members:["65754ade55df1cea083fdbb9"]) {
        id
    }
}

mutation {
    removePhaseMembers(id:"6592d9f0fc4b59f0f2b54b32", members:["65754ade55df1cea083fdbb9"]) {
        id
    }
}

mutation {
    changePhaseOrder(processId:"659271910603aab10cb73966", previousOrders: [1,2], newOrders: [2,1]) {
        id
    }
}

#------------------------------------------------------------------------------------

# Tasks

mutation {
    createTask(phaseId:"6592b6fe74edcbc2bf6eee99", title:"Database Design", description:"Create ER diagram of the system", endDate:"2020-12-28", timezoneOffset:330) {
        id
    }
}

mutation {
    createTask(phaseId:"6592b6fe74edcbc2bf6eee99", title:"UI Design", description:"Design the UI of frontend", endDate:"2020-12-29", timezoneOffset:330) {
        id
    }
}

mutation {
    updateTask(id:"6593a6b9c2306a1ad936ae9b", description:"Draw ER diagram of the system") {
        id
    }
}

query tasks {
    tasks(phaseId:"6592b6fe74edcbc2bf6eee99") {
        id
        phase {
            id
        }
        title
        description
        endDate
        endTime
        timezoneOffset
        status
        taskAssignees {
            id
            username
            firstName
            lastName
            gender
        }
    }
}

query task {
    task(id:"6593a6b9c2306a1ad936ae9b") {
        id
        phase {
            id
        }
        title
        description
        endDate
        endTime
        timezoneOffset
        status
        taskAssignees {
            id
            username
            firstName
            lastName
            gender
        }
    }
}

mutation{
    assignTask(id:"6593a6b9c2306a1ad936ae9b", assignees:["65754ade55df1cea083fdbb9","65755ce1663be023e8a16df5"]) {
        id
    }
}

mutation{
    unassignTask(id:"6593a6b9c2306a1ad936ae9b", assignees:["65754ade55df1cea083fdbb9"]) {
        id
    }
}

#------------------------------------------------------------------------------------

# messages

mutation {
    createPrivateMessage(receiverId:"65754ade55df1cea083fdbb9", content:"Hello, How are you?") {
        id
    }
}

query lastPrivateMessages {
    lastPrivateMessages {
        id
        sender {
            id
        }
        receiver {
            id
        }
        content
    }
}

query privateMessages {
    privateMessages(userId: "65754ade55df1cea083fdbb9", lastMessageIndex: 3, limit:2) {
        id
        sender {
            id
        }
        receiver {
            id
        }
        content
        index
    }
}

subscription{
    newMessage(wsToken:"dadb718315b21269bf4d8bcf23c18eae") {
        id
        content
        sender {
            id
            firstName
        }
        receiver {
            id
            firstName
        }
        project {
            id
        }
        phase {
            id
            title
        }
    }
}

mutation {
    createProjectMessage(projectId:"659251af749175ea95e8dfec", content:"Hello, How are you?") {
        id
    }
}

query lastProjectMessages {
    lastProjectMessages {
        id
        sender {
            id
        }
        project {
            id
        }
        content
    }
}