mutation {
    signUp(username:"SamC", password:"Banana@1234", firstName:"Sam", lastName:"Convoy", gender:"Male", country:"USA", primaryEmail:"SamConvoy@gmail.com"){
        firstName
    }
}

mutation {
    signUp(username:"JaneC", password:"Banana@1234", firstName:"Jane", lastName:"Convoy", gender:"Female", country:"USA", primaryEmail:"JaneConvoy@gmail.com"){
        firstName
    }
}

mutation {
    signIn(username:"SamC", password:"Banana@1234"){
        firstName
    }
}

mutation {
    signIn(username:"JaneC", password:"Banana@1234"){
        firstName
    }
}

mutation {
    signOut
}


mutation {
    createProject(title:"Project Alpha", description:"AI based FullStack Project") {
        id
    }
}

mutation {
    createProject(title:"Project Beta", description:"IOT based FullStack Project", members:["65755ce1663be023e8a16df5"]) {
        id
    }
}
