// Generate AI Answer for Forum Post Handler
import { getItem, putItem, updateItem } from '../shared/dynamodb.js';
import { getUserIdFromContext } from '../shared/auth.js';
import { generateId, getCurrentTimestamp } from '../shared/validation.js';
import { getParameter } from '../shared/ssm.js';
import { lambdaHandler, NotFoundError, AuthorizationError, ValidationError } from '../shared/errors.js';

// Gemini AI integration
async function generateAIAnswer(postTitle, postContent) {
  try {
    // Get Gemini API key from Parameter Store
    const apiKey = await getParameter('GEMINI_API_KEY');
    
    if (!apiKey) {
      throw new Error('Gemini API key not found in Parameter Store');
    }
    
    // Construct prompt for Gemini
    const prompt = `You are a helpful project management assistant. A team member has posted the following question in their project forum:

Title: ${postTitle}

Question: ${postContent}

Please provide a helpful, professional, and actionable answer to help them resolve their issue or answer their question. Keep the response concise (under 500 words) and practical.`;
    
    // Call Gemini API
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          contents: [{
            parts: [{
              text: prompt
            }]
          }],
          generationConfig: {
            temperature: 0.7,
            topK: 40,
            topP: 0.95,
            maxOutputTokens: 1024
          }
        })
      }
    );
    
    if (!response.ok) {
      const errorData = await response.json();
      console.error('Gemini API error:', errorData);
      throw new Error(`Gemini API error: ${response.status}`);
    }
    
    const data = await response.json();
    
    // Extract generated text
    if (!data.candidates || data.candidates.length === 0) {
      throw new Error('No response generated by Gemini');
    }
    
    const generatedText = data.candidates[0].content.parts[0].text;
    return generatedText;
    
  } catch (error) {
    console.error('Error generating AI answer:', error);
    throw new Error(`Failed to generate AI answer: ${error.message}`);
  }
}

async function generateAIAnswerHandler(event) {
  const { postId } = event.arguments;
  
  // Get authenticated user
  const userId = getUserIdFromContext(event.identity);
  
  // Get post
  const post = await getItem(`POST#${postId}`, 'METADATA');
  
  if (!post) {
    throw new NotFoundError('Post');
  }
  
  // Get project to verify membership
  const project = await getItem(`PROJECT#${post.projectId}`, 'METADATA');
  
  if (!project) {
    throw new NotFoundError('Project');
  }
  
  if (!project.memberIds.includes(userId)) {
    throw new AuthorizationError('You are not a member of this project');
  }
  
  // Generate AI answer
  let aiContent;
  try {
    aiContent = await generateAIAnswer(post.title, post.content);
  } catch (error) {
    throw new ValidationError(`Failed to generate AI answer: ${error.message}`);
  }
  
  // Generate reply ID
  const replyId = generateId();
  const timestamp = getCurrentTimestamp();
  
  // Create AI-generated reply
  const replyItem = {
    PK: `POST#${postId}`,
    SK: `REPLY#${replyId}`,
    EntityType: 'Reply',
    postId,
    replyId,
    authorId: 'AI_ASSISTANT', // Special ID for AI-generated content
    content: aiContent,
    isAIGenerated: true,
    createdAt: timestamp,
    updatedAt: timestamp
  };
  
  await putItem(replyItem);
  
  // Increment reply count on post
  await updateItem(
    `POST#${postId}`,
    'METADATA',
    'SET #replyCount = #replyCount + :inc, #updatedAt = :updatedAt',
    {
      '#replyCount': 'replyCount',
      '#updatedAt': 'updatedAt'
    },
    {
      ':inc': 1,
      ':updatedAt': timestamp
    }
  );
  
  // Update project-post relationship reply count
  await updateItem(
    `PROJECT#${post.projectId}`,
    `POST#${postId}`,
    'SET #replyCount = #replyCount + :inc, #updatedAt = :updatedAt',
    {
      '#replyCount': 'replyCount',
      '#updatedAt': 'updatedAt'
    },
    {
      ':inc': 1,
      ':updatedAt': timestamp
    }
  );
  
  // Return AI-generated reply
  return {
    id: replyId,
    content: aiContent,
    author: {
      id: 'AI_ASSISTANT',
      username: 'AI Assistant',
      firstName: 'AI',
      lastName: 'Assistant',
      gender: null,
      imageURL: null
    },
    isAIGenerated: true,
    createdAt: timestamp,
    updatedAt: timestamp
  };
}

export const handler = lambdaHandler(generateAIAnswerHandler);
