# Generate Configuration Script for Windows (PowerShell)
# Extract Terraform outputs and generate AWS configuration
# Usage: .\scripts\generate-config.ps1

$ErrorActionPreference = "Stop"

Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host "🔧 Generating Frontend Configuration" -ForegroundColor Green
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host ""

# Get current directory
$projectRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
if (-not $projectRoot) {
    $projectRoot = (Get-Location).Path
}

# Change to infrastructure directory
Set-Location "$projectRoot\infrastructure"

Write-Host "🔧 Extracting Terraform outputs..." -ForegroundColor Cyan

# Get Terraform outputs
try {
    $cognitoUserPoolId = (terraform output -raw cognito_user_pool_id 2>$null)
    $cognitoClientId = (terraform output -raw cognito_app_client_id 2>$null)
    $cognitoIdentityPoolId = (terraform output -raw cognito_identity_pool_id 2>$null)
    $cognitoDomain = (terraform output -raw cognito_domain 2>$null)
    $appsyncEndpoint = (terraform output -raw graphql_url 2>$null)
    $awsRegion = (terraform output -raw aws_region 2>$null)
    if (-not $awsRegion) { $awsRegion = "us-east-1" }
    $s3PrivateBucket = (terraform output -raw s3_private_bucket_name 2>$null)
    $s3PublicBucket = (terraform output -raw s3_public_bucket_name 2>$null)
} catch {
    Write-Host "❌ Error: Could not retrieve Terraform outputs." -ForegroundColor Red
    Write-Host "   Make sure Terraform has been applied successfully." -ForegroundColor Yellow
    Write-Host "   Run: cd infrastructure; terraform apply" -ForegroundColor Yellow
    exit 1
}

# Check if we got the outputs
if (-not $cognitoUserPoolId -or -not $appsyncEndpoint) {
    Write-Host "❌ Error: Could not retrieve Terraform outputs." -ForegroundColor Red
    Write-Host "   Make sure Terraform has been applied successfully." -ForegroundColor Yellow
    exit 1
}

Write-Host "✅ Terraform outputs retrieved successfully" -ForegroundColor Green
Write-Host ""
Write-Host "📝 Generating configuration files..." -ForegroundColor Cyan

# Return to project root
Set-Location $projectRoot

# Get current timestamp
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

# Generate frontend .env file
$envContent = @"
# AWS Configuration - Auto-generated by deploy script
# Generated at: $timestamp

AWS_REGION=$awsRegion
COGNITO_USER_POOL_ID=$cognitoUserPoolId
COGNITO_CLIENT_ID=$cognitoClientId
COGNITO_IDENTITY_POOL_ID=$cognitoIdentityPoolId
COGNITO_DOMAIN=$cognitoDomain
APPSYNC_ENDPOINT=$appsyncEndpoint
S3_BUCKET=$s3PrivateBucket
"@

$envContent | Out-File -FilePath "frontend\.env" -Encoding UTF8
Write-Host "Created frontend\.env" -ForegroundColor Green

# Generate aws-config.js with actual values
$awsConfigContent = @"
// AWS Amplify Configuration for Project Management App
// Auto-generated by deploy script at $timestamp

const awsConfig = {
  aws_project_region: '$awsRegion',
  
  Auth: {
    region: '$awsRegion',
    userPoolId: '$cognitoUserPoolId',
    userPoolWebClientId: '$cognitoClientId',
    identityPoolId: '$cognitoIdentityPoolId',
    mandatorySignIn: true,
    
    oauth: {
      domain: '$cognitoDomain',
      scope: ['email', 'openid', 'profile', 'aws.cognito.signin.user.admin'],
      redirectSignIn: 'exp://localhost:8081/',
      redirectSignOut: 'exp://localhost:8081/',
      responseType: 'code'
    }
  },
  
  aws_appsync_graphqlEndpoint: '$appsyncEndpoint',
  aws_appsync_region: '$awsRegion',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
  
  Storage: {
    AWSS3: {
      bucket: '$s3PrivateBucket',
      region: '$awsRegion'
    }
  }
};

export default awsConfig;

export const getConfig = (environment = 'development') => {
  return awsConfig;
};

export const validateConfig = () => {
  console.log('AWS configuration loaded from Terraform outputs');
  return true;
};
"@

$awsConfigContent | Out-File -FilePath "frontend\src\aws-config.js" -Encoding UTF8
Write-Host "Created frontend\src\aws-config.js" -ForegroundColor Green

# Display configuration summary
Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "AWS Configuration Summary" -ForegroundColor Yellow
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "Region:              $awsRegion"
Write-Host "User Pool ID:        $cognitoUserPoolId"
Write-Host "Client ID:           $cognitoClientId"
Write-Host "Identity Pool ID:    $cognitoIdentityPoolId"
Write-Host "AppSync Endpoint:    $appsyncEndpoint"
Write-Host "S3 Private Bucket:   $s3PrivateBucket"
Write-Host "S3 Public Bucket:    $s3PublicBucket"
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Configuration files generated successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "1. cd frontend"
Write-Host "2. npm install"
Write-Host "3. npm start"
Write-Host ""
