#!/bin/bash

# Script to extract Terraform outputs and generate AWS configuration
# Run this after Terraform deployment: ./scripts/generate-config.sh

set -e

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 Generating Frontend Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Get the script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Change to infrastructure directory
cd "${PROJECT_ROOT}/infrastructure"

# Get Terraform outputs
COGNITO_USER_POOL_ID=$(terraform output -raw cognito_user_pool_id 2>/dev/null || echo "")
COGNITO_CLIENT_ID=$(terraform output -raw cognito_client_id 2>/dev/null || echo "")
COGNITO_IDENTITY_POOL_ID=$(terraform output -raw cognito_identity_pool_id 2>/dev/null || echo "")
COGNITO_DOMAIN=$(terraform output -raw cognito_domain 2>/dev/null || echo "")
APPSYNC_ENDPOINT=$(terraform output -raw appsync_endpoint 2>/dev/null || echo "")
AWS_REGION=$(terraform output -raw aws_region 2>/dev/null || echo "us-east-1")
S3_PRIVATE_BUCKET=$(terraform output -raw s3_private_bucket 2>/dev/null || echo "")
S3_PUBLIC_BUCKET=$(terraform output -raw s3_public_bucket 2>/dev/null || echo "")

# Check if we got the outputs
if [ -z "$COGNITO_USER_POOL_ID" ] || [ -z "$APPSYNC_ENDPOINT" ]; then
    echo "❌ Error: Could not retrieve Terraform outputs."
    echo "   Make sure Terraform has been applied successfully."
    echo "   Run: cd infrastructure && terraform apply"
    exit 1
fi

echo "✅ Terraform outputs retrieved successfully"
echo ""
echo "📝 Generating configuration files..."

# Return to project root
cd "${PROJECT_ROOT}"

# Generate frontend .env file
cat > frontend/.env << EOF
# AWS Configuration - Auto-generated by deploy script
# Generated at: $(date)

AWS_REGION=${AWS_REGION}
COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
COGNITO_IDENTITY_POOL_ID=${COGNITO_IDENTITY_POOL_ID}
COGNITO_DOMAIN=${COGNITO_DOMAIN}
APPSYNC_ENDPOINT=${APPSYNC_ENDPOINT}
S3_BUCKET=${S3_PRIVATE_BUCKET}
EOF

echo "✅ Created frontend/.env"

# Generate aws-config.js with actual values
cat > frontend/src/aws-config.js << EOF
// AWS Amplify Configuration for Project Management App
// Auto-generated by deploy script at $(date)

const awsConfig = {
  aws_project_region: '${AWS_REGION}',
  
  Auth: {
    region: '${AWS_REGION}',
    userPoolId: '${COGNITO_USER_POOL_ID}',
    userPoolWebClientId: '${COGNITO_CLIENT_ID}',
    identityPoolId: '${COGNITO_IDENTITY_POOL_ID}',
    mandatorySignIn: true,
    
    oauth: {
      domain: '${COGNITO_DOMAIN}',
      scope: ['email', 'openid', 'profile', 'aws.cognito.signin.user.admin'],
      redirectSignIn: 'exp://localhost:8081/',
      redirectSignOut: 'exp://localhost:8081/',
      responseType: 'code'
    }
  },
  
  aws_appsync_graphqlEndpoint: '${APPSYNC_ENDPOINT}',
  aws_appsync_region: '${AWS_REGION}',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
  
  Storage: {
    AWSS3: {
      bucket: '${S3_PRIVATE_BUCKET}',
      region: '${AWS_REGION}'
    }
  }
};

export default awsConfig;

export const getConfig = (environment = 'development') => {
  return awsConfig;
};

export const validateConfig = () => {
  console.log('✅ AWS configuration loaded from Terraform outputs');
  return true;
};
EOF

echo "✅ Created frontend/src/aws-config.js"

# Display configuration summary
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 AWS Configuration Summary"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Region:              ${AWS_REGION}"
echo "User Pool ID:        ${COGNITO_USER_POOL_ID}"
echo "Client ID:           ${COGNITO_CLIENT_ID}"
echo "Identity Pool ID:    ${COGNITO_IDENTITY_POOL_ID}"
echo "AppSync Endpoint:    ${APPSYNC_ENDPOINT}"
echo "S3 Private Bucket:   ${S3_PRIVATE_BUCKET}"
echo "S3 Public Bucket:    ${S3_PUBLIC_BUCKET}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Configuration files generated successfully!"
echo ""
echo "Next steps:"
echo "1. cd frontend && npm install"
echo "2. npm start"
echo ""
